
Total number of parameters:  9231114
  0%|                                                                                                        | 0/20 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/home/ubuntu/21thanh.ht/imbalanced_dynamics/source/train_cifar10_noaccel.py", line 140, in <module>
    loss = criterion(outputs, targets)
  File "/home/ubuntu/miniconda3/envs/emthanhcv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/emthanhcv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/emthanhcv/lib/python3.10/site-packages/torch/nn/modules/loss.py", line 1185, in forward
    return F.cross_entropy(input, target, weight=self.weight,
  File "/home/ubuntu/miniconda3/envs/emthanhcv/lib/python3.10/site-packages/torch/nn/functional.py", line 3086, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cpu! (when checking argument for argument weight in method wrapper_CUDA_nll_loss_forward)